define({
  root: ({
    "instruction": "Add and configure geocode services or feature layers as search sources. These specified sources determine what is searchable within the search box.",
    "add": "Add Search Source",
    "addGeocoder": "Add Geocoder",
    "geocoder": "Geocoder",
    "setLayerSource": "Set Layer Source",
    "setGeocoderURL": "Set Geocoder URL",
    "searchableLayer": "Feature Layer",
    "name": "Name",
    "countryCode": "Country Code(s)",
    "countryCodeEg": "e.g. ",
    "countryCodeHint": "Leaving this value blank will search all countries",
    "locatorUrl": "Geocoder URL",
    "locatorName": "Geocoder Name",
    "locatorExample": "Example",
    "locatorWarning": "This version of geocoding service is not supported. The widget supports geocoding service 00.0 and above.",
    "locatorTips": "Suggestions are not available because the geocoding service doesn't support suggest capability.",
    "layerSource": "Layer Source",
    "searchLayerTips": "Suggestions are not available because the feature service doesn't support pagination capability.",
    "placeholder": "Placeholder Text",
    "searchFields": "Search Fields",
    "displayField": "Display Fields",
    "exactMatch": "Exact Match",
    "maxResults": "Maximum Results",
    "setSearchFields": "Set Search Fields",
    "set": "Set",
    "fieldSearchable": "searchable",
    "fieldName": "Name",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Cancel",
    "invalidUrlTip": "The URL you have entered is invalid or inaccessible.",
    "minCharToSearch": "Min character length",
    "moreDataMaxLimit":"More data max limit",
    "symbologySectionTitle":"Symbology",
    "polygonSymbol": "Polygon",
    "polyLineSymbol": "Line",
    "pointSymbol": "Point",
    "indicatorSectionTitle": "Indicator",
    "indicatorCheck": "Turn On Indicator",
    "indicatorSymbol": "Indicator Symbology",
    "customQuery": "Custom Query",
    "customQueryService": "Service URL",
    "customQueryParam": "Query Parameter",
    "customQueryResultsIdentifierField": "Results Identifer Field",
    "queryResponseFormat":"Format",
    "geometrySourceUrl": "Geometry Source",
    "geometrySourceQueryField":"Query Field",
    "extendedQueryUrl": "Extended Search",
    "extendedQueryField": "Extended Query Parameter",
    "resultsDisplay": "Results Display",
    "displayPopup": "Popup",
    "displayResultsPanel": "Results Panel",
    "displayNoResults": "Disabled",
    "zoomToScale": "Zoom to Scale",
    "zoomToFeatureExtent": "Zoom to Feature(s) Extent",
    "defaultZoomToScale": 1000,
    "defaultExtentPadding": 10,
    "displayManifestInfo": "Display manifest info on hover",
  })
});